version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://user:1@db:5432/tasks_db
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

volumes:
  grafana_data:
  jenkins_home:
