azure_subscription_id = "your-azure-subscription-id"
azure_tenant_id       = "your-azure-tenant-id"
azure_client_id       = "your-azure-client-id"
azure_client_secret   = "your-azure-client-secret"
gcp_project           = "your-gcp-project-id"
