# Dockerfile-flask
FROM python:3.10-slim

WORKDIR /app

# Copy requirements file and install dependencies
COPY app/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application source code
COPY app .

CMD ["python", "app.py"]
