FROM python:3.10-slim

WORKDIR /app

COPY digitalocean /app

COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt


EXPOSE 8000

CMD ["python", "digitalocean_exporter.py"]
