# Use Python slim image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy requirements.txt and validate the file exists
COPY digitalocean/requirements.txt /app/
RUN ls -la /app/requirements.txt \
    && cat /app/requirements.txt

# Install dependencies and verify Flask installation
RUN pip install --no-cache-dir -i https://pypi.org/simple -r requirements.txt


# Copy the application file
COPY digitalocean/digitalocean_exporter.py /app/

# Verify that the application file exists
RUN ls -la /app/digitalocean_exporter.py

# Expose the port
EXPOSE 8000

# Start the application
CMD ["python3", "digitalocean_exporter.py"]
