global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['flask_app:5000']

  - job_name: 'db'
    static_configs:
      - targets: ['db:5432']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cloudwatch'
    static_configs:
      - targets: ['cloudwatch-exporter:9106']

scrape_configs:
  - job_name: 'digitalocean'
    static_configs:
      - targets: ['46.101.243.196:8000']

  - job_name: 'aws'
    static_configs:
      - targets: ['54.218.103.87:9106']

